### ISSUE TITLE
UnicodeDecodeError on %%async_run

### ISSUE THREAD

**Issue by bofm** [leriomaggio/async-ipython-magic#1]
Hi, 

I tried to play with this and got the error.
The notebook is the one from the examples.

After executing 
```
%%async_run 
N = 10**s
print(N)
```
the error appeared in the console.

```
ERROR:tornado.application:Uncaught exception in /ws/PYTHON---9c4c6b81-49b3-4977-9093-b04f5bbf3328
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/websocket.py", line 412, in _run_callback
    callback(*args, **kwargs)
  File "/Users/sergey/.ipython/profile_default/startup/run_async/run_server.py", line 181, in on_message
    data = json.loads(message)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 349, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I used Jupyter Notebook 5.0.0 on Python 3.6 on MacOS

**Comment by ttkopec** [comment]
Hi,
I'm facing same issue. Have you maybe found a solution?
